//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/project/Scripts/Actionns/InputActionnsMouse.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace InputActionns
{
    public partial class @InputActionnsMouse: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputActionnsMouse()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActionnsMouse"",
    ""maps"": [
        {
            ""name"": ""Movment"",
            ""id"": ""d663c397-7573-4132-91a2-9b10283d9433"",
            ""actions"": [
                {
                    ""name"": ""HouseMovment"",
                    ""type"": ""Value"",
                    ""id"": ""3e290a3f-c7c4-45b2-bcea-cdfbf3f69868"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraMovment"",
                    ""type"": ""Value"",
                    ""id"": ""0da435ea-d152-4beb-86aa-053ce0bb159c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""KeyDetect"",
                    ""type"": ""Button"",
                    ""id"": ""77624c91-3b9d-46f6-be90-b44012a43ba5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""CameraMovment"",
                    ""id"": ""bb364fce-c581-4885-82c8-b7246346d606"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovment"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""373f29b9-63bd-4704-b8f2-fcce44440891"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""25a13ca6-5773-4ac3-83d1-35f8cdd2b5ee"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""857476ae-c94d-46ea-a69b-6c37077a47ce"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5d44e4e-c3e1-4b6f-8a58-51f067ad7ce4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyDetect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2029576-7827-4635-992c-b2b316bc89af"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyDetect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2052ffbe-4020-4bc8-821a-35a3e7cd50c7"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HouseMovment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Movment
            m_Movment = asset.FindActionMap("Movment", throwIfNotFound: true);
            m_Movment_HouseMovment = m_Movment.FindAction("HouseMovment", throwIfNotFound: true);
            m_Movment_CameraMovment = m_Movment.FindAction("CameraMovment", throwIfNotFound: true);
            m_Movment_KeyDetect = m_Movment.FindAction("KeyDetect", throwIfNotFound: true);
        }

        ~@InputActionnsMouse()
        {
            UnityEngine.Debug.Assert(!m_Movment.enabled, "This will cause a leak and performance issues, InputActionnsMouse.Movment.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Movment
        private readonly InputActionMap m_Movment;
        private List<IMovmentActions> m_MovmentActionsCallbackInterfaces = new List<IMovmentActions>();
        private readonly InputAction m_Movment_HouseMovment;
        private readonly InputAction m_Movment_CameraMovment;
        private readonly InputAction m_Movment_KeyDetect;
        public struct MovmentActions
        {
            private @InputActionnsMouse m_Wrapper;
            public MovmentActions(@InputActionnsMouse wrapper) { m_Wrapper = wrapper; }
            public InputAction @HouseMovment => m_Wrapper.m_Movment_HouseMovment;
            public InputAction @CameraMovment => m_Wrapper.m_Movment_CameraMovment;
            public InputAction @KeyDetect => m_Wrapper.m_Movment_KeyDetect;
            public InputActionMap Get() { return m_Wrapper.m_Movment; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MovmentActions set) { return set.Get(); }
            public void AddCallbacks(IMovmentActions instance)
            {
                if (instance == null || m_Wrapper.m_MovmentActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_MovmentActionsCallbackInterfaces.Add(instance);
                @HouseMovment.started += instance.OnHouseMovment;
                @HouseMovment.performed += instance.OnHouseMovment;
                @HouseMovment.canceled += instance.OnHouseMovment;
                @CameraMovment.started += instance.OnCameraMovment;
                @CameraMovment.performed += instance.OnCameraMovment;
                @CameraMovment.canceled += instance.OnCameraMovment;
                @KeyDetect.started += instance.OnKeyDetect;
                @KeyDetect.performed += instance.OnKeyDetect;
                @KeyDetect.canceled += instance.OnKeyDetect;
            }

            private void UnregisterCallbacks(IMovmentActions instance)
            {
                @HouseMovment.started -= instance.OnHouseMovment;
                @HouseMovment.performed -= instance.OnHouseMovment;
                @HouseMovment.canceled -= instance.OnHouseMovment;
                @CameraMovment.started -= instance.OnCameraMovment;
                @CameraMovment.performed -= instance.OnCameraMovment;
                @CameraMovment.canceled -= instance.OnCameraMovment;
                @KeyDetect.started -= instance.OnKeyDetect;
                @KeyDetect.performed -= instance.OnKeyDetect;
                @KeyDetect.canceled -= instance.OnKeyDetect;
            }

            public void RemoveCallbacks(IMovmentActions instance)
            {
                if (m_Wrapper.m_MovmentActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IMovmentActions instance)
            {
                foreach (var item in m_Wrapper.m_MovmentActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_MovmentActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public MovmentActions @Movment => new MovmentActions(this);
        public interface IMovmentActions
        {
            void OnHouseMovment(InputAction.CallbackContext context);
            void OnCameraMovment(InputAction.CallbackContext context);
            void OnKeyDetect(InputAction.CallbackContext context);
        }
    }
}
